version: "3.9"

services:
    app:
        build: .
        ports:
            -   ${APP_PORT}:${APP_PORT}
        expose:
            -   ${APP_PORT}
        env_file:
            -   .env
        depends_on:
            db:
                condition: service_healthy
        networks:
            -   localhost
    db:
        container_name: db
        image: postgres
        ports:
            -   ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            -   postgres:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            -   localhost

volumes:
    postgres:

networks:
    localhost:
        driver: bridge
        name: localhost
